/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as Ads01RouteImport } from './routes/ads01'
import { Route as BarbeaRouteImport } from './routes/barbea'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as SalaodeRouteImport } from './routes/salaode'
import { Route as TerapiRouteImport } from './routes/terapi'
import { Route as WhatsRouteImport } from './routes/whats'
import { Route as ApiPublicInfinitepayWebhookRouteImport } from './routes/api/public/infinitepay/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Ads01Route = Ads01RouteImport.update({
  id: '/ads01',
  path: '/ads01',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeaRoute = BarbeaRouteImport.update({
  id: '/barbea',
  path: '/barbea',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaodeRoute = SalaodeRouteImport.update({
  id: '/salaode',
  path: '/salaode',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapiRoute = TerapiRouteImport.update({
  id: '/terapi',
  path: '/terapi',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsRoute = WhatsRouteImport.update({
  id: '/whats',
  path: '/whats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInfinitepayWebhookRoute =
  ApiPublicInfinitepayWebhookRouteImport.update({
    id: '/api/public/infinitepay/webhook',
    path: '/api/public/infinitepay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads01': typeof Ads01Route
  '/barbea': typeof BarbeaRoute
  '/delivery': typeof DeliveryRoute
  '/painel': typeof PainelRoute
  '/pedido': typeof PedidoRoute
  '/recuperar': typeof RecuperarRoute
  '/salaode': typeof SalaodeRoute
  '/terapi': typeof TerapiRoute
  '/whats': typeof WhatsRoute
  '/api/public/infinitepay/webhook': typeof ApiPublicInfinitepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads01': typeof Ads01Route
  '/barbea': typeof BarbeaRoute
  '/delivery': typeof DeliveryRoute
  '/painel': typeof PainelRoute
  '/pedido': typeof PedidoRoute
  '/recuperar': typeof RecuperarRoute
  '/salaode': typeof SalaodeRoute
  '/terapi': typeof TerapiRoute
  '/whats': typeof WhatsRoute
  '/api/public/infinitepay/webhook': typeof ApiPublicInfinitepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads01': typeof Ads01Route
  '/barbea': typeof BarbeaRoute
  '/delivery': typeof DeliveryRoute
  '/painel': typeof PainelRoute
  '/pedido': typeof PedidoRoute
  '/recuperar': typeof RecuperarRoute
  '/salaode': typeof SalaodeRoute
  '/terapi': typeof TerapiRoute
  '/whats': typeof WhatsRoute
  '/api/public/infinitepay/webhook': typeof ApiPublicInfinitepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ads01'
    | '/barbea'
    | '/delivery'
    | '/painel'
    | '/pedido'
    | '/recuperar'
    | '/salaode'
    | '/terapi'
    | '/whats'
    | '/api/public/infinitepay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ads01'
    | '/barbea'
    | '/delivery'
    | '/painel'
    | '/pedido'
    | '/recuperar'
    | '/salaode'
    | '/terapi'
    | '/whats'
    | '/api/public/infinitepay/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ads01'
    | '/barbea'
    | '/delivery'
    | '/painel'
    | '/pedido'
    | '/recuperar'
    | '/salaode'
    | '/terapi'
    | '/whats'
    | '/api/public/infinitepay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  Ads01Route: typeof Ads01Route
  BarbeaRoute: typeof BarbeaRoute
  DeliveryRoute: typeof DeliveryRoute
  PainelRoute: typeof PainelRoute
  PedidoRoute: typeof PedidoRoute
  RecuperarRoute: typeof RecuperarRoute
  SalaodeRoute: typeof SalaodeRoute
  TerapiRoute: typeof TerapiRoute
  WhatsRoute: typeof WhatsRoute
  ApiPublicInfinitepayWebhookRoute: typeof ApiPublicInfinitepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads01': {
      id: '/ads01'
      path: '/ads01'
      fullPath: '/ads01'
      preLoaderRoute: typeof Ads01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbea': {
      id: '/barbea'
      path: '/barbea'
      fullPath: '/barbea'
      preLoaderRoute: typeof BarbeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaode': {
      id: '/salaode'
      path: '/salaode'
      fullPath: '/salaode'
      preLoaderRoute: typeof SalaodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapi': {
      id: '/terapi'
      path: '/terapi'
      fullPath: '/terapi'
      preLoaderRoute: typeof TerapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats': {
      id: '/whats'
      path: '/whats'
      fullPath: '/whats'
      preLoaderRoute: typeof WhatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infinitepay/webhook': {
      id: '/api/public/infinitepay/webhook'
      path: '/api/public/infinitepay/webhook'
      fullPath: '/api/public/infinitepay/webhook'
      preLoaderRoute: typeof ApiPublicInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  Ads01Route: Ads01Route,
  BarbeaRoute: BarbeaRoute,
  DeliveryRoute: DeliveryRoute,
  PainelRoute: PainelRoute,
  PedidoRoute: PedidoRoute,
  RecuperarRoute: RecuperarRoute,
  SalaodeRoute: SalaodeRoute,
  TerapiRoute: TerapiRoute,
  WhatsRoute: WhatsRoute,
  ApiPublicInfinitepayWebhookRoute: ApiPublicInfinitepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
